version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "165270212723"
    AWS_REGION: "us-east-1"
    REPOSITORY_NAME: "odoo-ci/cd"
    CLUSTER_NAME: "demo-cluster"
    SERVICE_NAME: "odoo-service-6xfmftdl"

phases:
  pre_build:
    commands:
      - set -e
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - export IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME
      - echo Repository URI is $REPOSITORY_URI
      - echo Image tag is $IMAGE_TAG
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Updating ECS service with new image...
      - |
        aws ecs update-service \
          --cluster $CLUSTER_NAME \
          --service $SERVICE_NAME \
          --force-new-deployment \
          --region $AWS_REGION

artifacts:
  files: []
